### ISSUE TITLE
Data Dictionary

### ISSUE THREAD

**Issue by Crghilardi** [New-Jersey-Forest-Service/InventoryErrorMLSolutions#1]
I took a look at Tim's work and it seems well done. I tried to create a new script to try something but I don't understand what half the column names are. 

@wzip  can we get some descriptions? I see stand, but what is cluster? I don't see plots anywhere or you guys are calling it something different.

**Comment by wzip** [comment]
Cluster is the plot identifier (as in a cluster of nested subplots), and stand represents the forest type.  It is a bit of a mishmash of data from different sources.  Now that we have our interns, I can get them to spend some time documenting how this data is put together.

**Comment by Crghilardi** [comment]
Ok, that makes sense. 

Here is a copy-pasteable list of the columns in the FinalOverObTableWAR. Would it be any easier to put the cruise specs manual somewhere people can reach it?

CLUSTER
ID
tree_obs_id
tree_spp
tree_dbh
tree_stems
tree_height
source_tree_height
tree_crown_class
source_tree_crown_class
tree_crown_cond
tree_height_class
source_tree_height_class
source_tree_user2
tree_stems_per
tree_ba
tree_rel_dens
tree_timber
source_tree_timber
tree_product
source_tree_product
tree_saw_ht
source_tree_saw_ht
tree_pulp_ht
source_tree_pulp_ht
tree_merch_ht
tree_bdft_vol
tree_net_bdft_vol
tree_saw_vol
tree_net_saw_vol
tree_pulp_vol
tree_net_pulp_vol
tree_cuft_vol
tree_net_cuft_vol
tree_biomass_root
tree_biomass_branch
tree_biomass_stem
tree_biomass_bark
tree_biomass_foliage
tree_biomass_above
tree_biomass_total
tree_cord_vol
tree_net_cord_vol
tree_ton_vol
tree_net_ton_vol
tree_pulp_cord_vol
tree_net_pulp_cord_vol
tree_pulp_ton_vol
tree_net_pulp_ton_vol
tree_saw_cord_vol
tree_net_saw_cord_vol
tree_saw_ton_vol
tree_net_saw_ton_vol
OverOb_wOverIDForTypBAFGrndPresCrzrSoilWet_over_id
stand_id
STAND
inventory_over_baf
GrndQUIL
GrndSMILA2
CRUISER
MUSYM
Wetland
CountOfOVER_OBS
OverObs_CountCheck_over_id
under_id
SumOfunder_count

**Comment by timbo112711** [comment]
I think having some sort of data lookup (dictionary), maybe just a text file or a word doc, that has each description on the variables we are using for this error correction. What do you two think about putting this data dict in a folder called Docs/Data?

**Comment by Crghilardi** [comment]
closing after ccd73df9a5cb67edbe2ed45cd8965f0816852cc1
